/*
 * This file was automatically generated by EvoSuite
 * Tue Apr 18 06:02:49 GMT 2017
 */

package edu.osu.cs362;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import edu.osu.cs362.Program;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Program_ESTest extends Program_ESTest_scaffolding {

  //Test case number: 0
  /*
   * 4 covered goals:
   * Goal 1. edu.osu.cs362.Program.<init>()V: root-Branch
   * Goal 2. Branch edu.osu.cs362.Program.<init>()V: root-Branch in context: edu.osu.cs362.Program:<init>()V
   * Goal 3. [METHOD] edu.osu.cs362.Program.<init>()V
   * Goal 4. [METHODNOEX] edu.osu.cs362.Program.<init>()V
   */

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Program program0 = new Program();
  }

  //Test case number: 1
  /*
   * 109 covered goals:
   * Goal 1. edu.osu.cs362.Program.main([Ljava/lang/String;)V: root-Branch
   * Goal 2. edu.osu.cs362.Program.sum([I)I: I12 Branch 1 IF_ICMPGE L25 - true
   * Goal 3. edu.osu.cs362.Program.sum([I)I: I12 Branch 1 IF_ICMPGE L25 - false
   * Goal 4. edu.osu.cs362.Program.product([I)I: I12 Branch 2 IF_ICMPGE L33 - false
   * Goal 5. Branch edu.osu.cs362.Program.main([Ljava/lang/String;)V: root-Branch in context: edu.osu.cs362.Program:main([Ljava/lang/String;)V
   * Goal 6. Branch edu.osu.cs362.Program.sum([I)I: I12 Branch 1 IF_ICMPGE L25 - true in context: 
   * Goal 7. Branch edu.osu.cs362.Program.sum([I)I: I12 Branch 1 IF_ICMPGE L25 - false in context: 
   * Goal 8. Branch edu.osu.cs362.Program.product([I)I: I12 Branch 2 IF_ICMPGE L33 - false in context: 
   * Goal 9. main([Ljava/lang/String;)V_java.lang.ArrayIndexOutOfBoundsException_IMPLICIT
   * Goal 10. edu.osu.cs362.Program.main([Ljava/lang/String;)V: Line 6
   * Goal 11. edu.osu.cs362.Program.main([Ljava/lang/String;)V: Line 8
   * Goal 12. edu.osu.cs362.Program.main([Ljava/lang/String;)V: Line 9
   * Goal 13. edu.osu.cs362.Program.main([Ljava/lang/String;)V: Line 11
   * Goal 14. edu.osu.cs362.Program.product([I)I: Line 32
   * Goal 15. edu.osu.cs362.Program.product([I)I: Line 33
   * Goal 16. edu.osu.cs362.Program.product([I)I: Line 34
   * Goal 17. edu.osu.cs362.Program.sum([I)I: Line 24
   * Goal 18. edu.osu.cs362.Program.sum([I)I: Line 25
   * Goal 19. edu.osu.cs362.Program.sum([I)I: Line 26
   * Goal 20. edu.osu.cs362.Program.sum([I)I: Line 28
   * Goal 21. [METHOD] edu.osu.cs362.Program.main([Ljava/lang/String;)V
   * Goal 22. Weak Mutation 0: edu.osu.cs362.Program.main([Ljava/lang/String;)V:6 - ReplaceConstant - 5 -> 0
   * Goal 23. Weak Mutation 1: edu.osu.cs362.Program.main([Ljava/lang/String;)V:6 - ReplaceConstant - 5 -> 1
   * Goal 24. Weak Mutation 2: edu.osu.cs362.Program.main([Ljava/lang/String;)V:6 - ReplaceConstant - 5 -> -1
   * Goal 25. Weak Mutation 3: edu.osu.cs362.Program.main([Ljava/lang/String;)V:6 - ReplaceConstant - 5 -> 4
   * Goal 26. Weak Mutation 4: edu.osu.cs362.Program.main([Ljava/lang/String;)V:6 - ReplaceConstant - 5 -> 6
   * Goal 27. Weak Mutation 5: edu.osu.cs362.Program.main([Ljava/lang/String;)V:6 - ReplaceConstant - 0 -> 1
   * Goal 28. Weak Mutation 6: edu.osu.cs362.Program.main([Ljava/lang/String;)V:6 - ReplaceConstant - 1 -> 0
   * Goal 29. Weak Mutation 7: edu.osu.cs362.Program.main([Ljava/lang/String;)V:6 - ReplaceConstant - 1 -> 0
   * Goal 30. Weak Mutation 8: edu.osu.cs362.Program.main([Ljava/lang/String;)V:6 - ReplaceConstant - 2 -> 0
   * Goal 31. Weak Mutation 9: edu.osu.cs362.Program.main([Ljava/lang/String;)V:6 - ReplaceConstant - 2 -> 1
   * Goal 32. Weak Mutation 10: edu.osu.cs362.Program.main([Ljava/lang/String;)V:6 - ReplaceConstant - 2 -> -1
   * Goal 33. Weak Mutation 11: edu.osu.cs362.Program.main([Ljava/lang/String;)V:6 - ReplaceConstant - 2 -> 3
   * Goal 34. Weak Mutation 12: edu.osu.cs362.Program.main([Ljava/lang/String;)V:6 - ReplaceConstant - 2 -> 0
   * Goal 35. Weak Mutation 13: edu.osu.cs362.Program.main([Ljava/lang/String;)V:6 - ReplaceConstant - 2 -> 1
   * Goal 36. Weak Mutation 14: edu.osu.cs362.Program.main([Ljava/lang/String;)V:6 - ReplaceConstant - 2 -> -1
   * Goal 37. Weak Mutation 15: edu.osu.cs362.Program.main([Ljava/lang/String;)V:6 - ReplaceConstant - 2 -> 3
   * Goal 38. Weak Mutation 16: edu.osu.cs362.Program.main([Ljava/lang/String;)V:6 - ReplaceConstant - 3 -> 0
   * Goal 39. Weak Mutation 17: edu.osu.cs362.Program.main([Ljava/lang/String;)V:6 - ReplaceConstant - 3 -> 1
   * Goal 40. Weak Mutation 18: edu.osu.cs362.Program.main([Ljava/lang/String;)V:6 - ReplaceConstant - 3 -> -1
   * Goal 41. Weak Mutation 19: edu.osu.cs362.Program.main([Ljava/lang/String;)V:6 - ReplaceConstant - 3 -> 2
   * Goal 42. Weak Mutation 20: edu.osu.cs362.Program.main([Ljava/lang/String;)V:6 - ReplaceConstant - 3 -> 4
   * Goal 43. Weak Mutation 21: edu.osu.cs362.Program.main([Ljava/lang/String;)V:6 - ReplaceConstant - 3 -> 0
   * Goal 44. Weak Mutation 22: edu.osu.cs362.Program.main([Ljava/lang/String;)V:6 - ReplaceConstant - 3 -> 1
   * Goal 45. Weak Mutation 23: edu.osu.cs362.Program.main([Ljava/lang/String;)V:6 - ReplaceConstant - 3 -> -1
   * Goal 46. Weak Mutation 24: edu.osu.cs362.Program.main([Ljava/lang/String;)V:6 - ReplaceConstant - 3 -> 2
   * Goal 47. Weak Mutation 25: edu.osu.cs362.Program.main([Ljava/lang/String;)V:6 - ReplaceConstant - 3 -> 4
   * Goal 48. Weak Mutation 26: edu.osu.cs362.Program.main([Ljava/lang/String;)V:6 - ReplaceConstant - 4 -> 0
   * Goal 49. Weak Mutation 27: edu.osu.cs362.Program.main([Ljava/lang/String;)V:6 - ReplaceConstant - 4 -> 1
   * Goal 50. Weak Mutation 28: edu.osu.cs362.Program.main([Ljava/lang/String;)V:6 - ReplaceConstant - 4 -> -1
   * Goal 51. Weak Mutation 29: edu.osu.cs362.Program.main([Ljava/lang/String;)V:6 - ReplaceConstant - 4 -> 3
   * Goal 52. Weak Mutation 30: edu.osu.cs362.Program.main([Ljava/lang/String;)V:6 - ReplaceConstant - 4 -> 5
   * Goal 53. Weak Mutation 31: edu.osu.cs362.Program.main([Ljava/lang/String;)V:6 - ReplaceConstant - 4 -> 0
   * Goal 54. Weak Mutation 32: edu.osu.cs362.Program.main([Ljava/lang/String;)V:6 - ReplaceConstant - 4 -> 1
   * Goal 55. Weak Mutation 33: edu.osu.cs362.Program.main([Ljava/lang/String;)V:6 - ReplaceConstant - 4 -> -1
   * Goal 56. Weak Mutation 34: edu.osu.cs362.Program.main([Ljava/lang/String;)V:6 - ReplaceConstant - 4 -> 3
   * Goal 57. Weak Mutation 35: edu.osu.cs362.Program.main([Ljava/lang/String;)V:6 - ReplaceConstant - 4 -> 5
   * Goal 58. Weak Mutation 36: edu.osu.cs362.Program.main([Ljava/lang/String;)V:6 - ReplaceConstant - 5 -> 0
   * Goal 59. Weak Mutation 37: edu.osu.cs362.Program.main([Ljava/lang/String;)V:6 - ReplaceConstant - 5 -> 1
   * Goal 60. Weak Mutation 38: edu.osu.cs362.Program.main([Ljava/lang/String;)V:6 - ReplaceConstant - 5 -> -1
   * Goal 61. Weak Mutation 39: edu.osu.cs362.Program.main([Ljava/lang/String;)V:6 - ReplaceConstant - 5 -> 4
   * Goal 62. Weak Mutation 40: edu.osu.cs362.Program.main([Ljava/lang/String;)V:6 - ReplaceConstant - 5 -> 6
   * Goal 63. Weak Mutation 41: edu.osu.cs362.Program.main([Ljava/lang/String;)V:9 - ReplaceConstant - The sum of the numbers was  -> 
   * Goal 64. Weak Mutation 42: edu.osu.cs362.Program.main([Ljava/lang/String;)V:9 - InsertUnaryOp Negation of sum
   * Goal 65. Weak Mutation 43: edu.osu.cs362.Program.main([Ljava/lang/String;)V:9 - InsertUnaryOp IINC 1 sum
   * Goal 66. Weak Mutation 44: edu.osu.cs362.Program.main([Ljava/lang/String;)V:9 - InsertUnaryOp IINC -1 sum
   * Goal 67. Weak Mutation 58: edu.osu.cs362.Program.sum([I)I:24 - ReplaceConstant - 0 -> 1
   * Goal 68. Weak Mutation 59: edu.osu.cs362.Program.sum([I)I:25 - ReplaceConstant - 0 -> 1
   * Goal 69. Weak Mutation 60: edu.osu.cs362.Program.sum([I)I:25 - ReplaceVariable i -> sum
   * Goal 70. Weak Mutation 61: edu.osu.cs362.Program.sum([I)I:25 - InsertUnaryOp Negation of i
   * Goal 71. Weak Mutation 62: edu.osu.cs362.Program.sum([I)I:25 - InsertUnaryOp IINC 1 i
   * Goal 72. Weak Mutation 63: edu.osu.cs362.Program.sum([I)I:25 - InsertUnaryOp IINC -1 i
   * Goal 73. Weak Mutation 64: edu.osu.cs362.Program.sum([I)I:25 - ReplaceComparisonOperator >= -> -1
   * Goal 74. Weak Mutation 65: edu.osu.cs362.Program.sum([I)I:25 - ReplaceComparisonOperator >= -> >
   * Goal 75. Weak Mutation 79: edu.osu.cs362.Program.sum([I)I:25 - ReplaceVariable i -> sum
   * Goal 76. Weak Mutation 67: edu.osu.cs362.Program.sum([I)I:26 - ReplaceVariable sum -> i
   * Goal 77. Weak Mutation 68: edu.osu.cs362.Program.sum([I)I:26 - InsertUnaryOp Negation of sum
   * Goal 78. Weak Mutation 69: edu.osu.cs362.Program.sum([I)I:26 - InsertUnaryOp IINC 1 sum
   * Goal 79. Weak Mutation 70: edu.osu.cs362.Program.sum([I)I:26 - InsertUnaryOp IINC -1 sum
   * Goal 80. Weak Mutation 71: edu.osu.cs362.Program.sum([I)I:26 - ReplaceVariable i -> sum
   * Goal 81. Weak Mutation 72: edu.osu.cs362.Program.sum([I)I:26 - InsertUnaryOp Negation of i
   * Goal 82. Weak Mutation 73: edu.osu.cs362.Program.sum([I)I:26 - InsertUnaryOp IINC 1 i
   * Goal 83. Weak Mutation 74: edu.osu.cs362.Program.sum([I)I:26 - InsertUnaryOp IINC -1 i
   * Goal 84. Weak Mutation 75: edu.osu.cs362.Program.sum([I)I:26 - ReplaceArithmeticOperator + -> %
   * Goal 85. Weak Mutation 76: edu.osu.cs362.Program.sum([I)I:26 - ReplaceArithmeticOperator + -> -
   * Goal 86. Weak Mutation 77: edu.osu.cs362.Program.sum([I)I:26 - ReplaceArithmeticOperator + -> *
   * Goal 87. Weak Mutation 78: edu.osu.cs362.Program.sum([I)I:26 - ReplaceArithmeticOperator + -> /
   * Goal 88. Weak Mutation 80: edu.osu.cs362.Program.sum([I)I:28 - InsertUnaryOp Negation of sum
   * Goal 89. Weak Mutation 81: edu.osu.cs362.Program.sum([I)I:28 - InsertUnaryOp IINC 1 sum
   * Goal 90. Weak Mutation 82: edu.osu.cs362.Program.sum([I)I:28 - InsertUnaryOp IINC -1 sum
   * Goal 91. Weak Mutation 83: edu.osu.cs362.Program.product([I)I:32 - ReplaceConstant - 1 -> 0
   * Goal 92. Weak Mutation 84: edu.osu.cs362.Program.product([I)I:33 - ReplaceConstant - 0 -> 1
   * Goal 93. Weak Mutation 85: edu.osu.cs362.Program.product([I)I:33 - ReplaceVariable i -> product
   * Goal 94. Weak Mutation 86: edu.osu.cs362.Program.product([I)I:33 - InsertUnaryOp Negation of i
   * Goal 95. Weak Mutation 87: edu.osu.cs362.Program.product([I)I:33 - InsertUnaryOp IINC 1 i
   * Goal 96. Weak Mutation 88: edu.osu.cs362.Program.product([I)I:33 - InsertUnaryOp IINC -1 i
   * Goal 97. Weak Mutation 89: edu.osu.cs362.Program.product([I)I:33 - ReplaceComparisonOperator >= -> -1
   * Goal 98. Weak Mutation 104: edu.osu.cs362.Program.product([I)I:33 - ReplaceVariable i -> product
   * Goal 99. Weak Mutation 92: edu.osu.cs362.Program.product([I)I:34 - ReplaceVariable product -> i
   * Goal 100. Weak Mutation 93: edu.osu.cs362.Program.product([I)I:34 - InsertUnaryOp Negation of product
   * Goal 101. Weak Mutation 94: edu.osu.cs362.Program.product([I)I:34 - InsertUnaryOp IINC 1 product
   * Goal 102. Weak Mutation 95: edu.osu.cs362.Program.product([I)I:34 - InsertUnaryOp IINC -1 product
   * Goal 103. Weak Mutation 96: edu.osu.cs362.Program.product([I)I:34 - ReplaceVariable i -> product
   * Goal 104. Weak Mutation 97: edu.osu.cs362.Program.product([I)I:34 - InsertUnaryOp Negation of i
   * Goal 105. Weak Mutation 98: edu.osu.cs362.Program.product([I)I:34 - InsertUnaryOp IINC 1 i
   * Goal 106. Weak Mutation 99: edu.osu.cs362.Program.product([I)I:34 - InsertUnaryOp IINC -1 i
   * Goal 107. Weak Mutation 100: edu.osu.cs362.Program.product([I)I:34 - ReplaceArithmeticOperator * -> +
   * Goal 108. Weak Mutation 101: edu.osu.cs362.Program.product([I)I:34 - ReplaceArithmeticOperator * -> %
   * Goal 109. Weak Mutation 102: edu.osu.cs362.Program.product([I)I:34 - ReplaceArithmeticOperator * -> -
   */

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      String[] stringArray0 = new String[1];
      // Undeclared exception!
      try { 
        Program.main(stringArray0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // -1
         //
         assertThrownBy("edu.osu.cs362.Program", e);
      }
  }
}
